version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: snackshop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass snackshop
    networks:
      - snackshop_network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  snackshop_network:
    driver: bridge 